---
#                   _
#   __ _ _ __   ___| |__   ___  _ __ ___
#  / _` | '_ \ / __| '_ \ / _ \| '__/ __|
# | (_| | | | | (__| | | | (_) | |  \__ \
#  \__,_|_| |_|\___|_| |_|\___/|_|  |___/
_anchors:
- &builder_common_options
  boot_wait: '{{ user `boot_wait` }}'

  communicator: '{{ user `communicator` }}'
# floppy_dirs: ([]string)
# floppy_files: ([]string)
# floppy_label: 'cidata'
# http_bind_address: 0.0.0.0
  http_directory: '{{ user `http_directory` }}'
  http_port_max: '{{ user `http_port_max` }}'
  http_port_min: '{{ user `http_port_min` }}'
  iso_checksum: '{{ user `iso_checksum` }}'
  iso_target_extension: iso
  iso_target_path: '{{ user `packer_cache_dir` }}/{{ user `iso_file` }}'
# iso_url: (string)
  iso_urls:
  - '{{ user `iso_path_internal` }}/{{ user `iso_file` }}'
  - '{{ user `iso_path_external` }}/{{ user `iso_file` }}'
# pause_before_connecting: '{{ user `pause_before_connecting` }}'
  shutdown_command: echo '{{ user `ssh_password` }}' | sudo -E -S poweroff
  shutdown_timeout: '{{ user `shutdown_timeout` }}'
  vm_name: '{{ user `vm_name` }}'

- &builder_edge_options
  cpus: '{{ user `cpus` }}'
  disk_size: '{{ user `disk_size` }}'
  headless: '{{ user `headless` }}'
  host_port_max: '{{ user `host_port_max` }}'
  host_port_min: '{{ user `host_port_min` }}'
# http_bind_address: 0.0.0.0
  memory: '{{ user `memory` }}'
  output_directory: '{{ user `output_directory` }}'
# pause_before_connecting: '{{ user `pause_before_connecting` }}'
  skip_nat_mapping: false


#  _           _ _     _
# | |__  _   _(_) | __| | ___ _ __ ___
# | '_ \| | | | | |/ _` |/ _ \ '__/ __|
# | |_) | |_| | | | (_| |  __/ |  \__ \
# |_.__/ \__,_|_|_|\__,_|\___|_|  |___/
builders:
#                                                    __ _  ___ _ __ ___  _   _
#                                                   / _` |/ _ \ '_ ` _ \| | | |
#                                                  | (_| |  __/ | | | | | |_| |
#                                                   \__, |\___|_| |_| |_|\__,_|
#                                                      |_|
- <<: [*builder_common_options, *builder_edge_options]
  accelerator: kvm
  disk_cache: writeback
  disk_compression: false
  disk_discard: ignore
  disk_image: false
  disk_interface: virtio-scsi
  format: raw
  iso_skip_cache: false
  machine_type: pc
  name: qemu
  net_device: virtio-net
  qemu_binary: '{{ user `qemu_binary` }}'
  skip_compaction: true
  type: qemu
  use_default_display: true
  vnc_bind_address: '{{ user `vnc_vrdp_bind_address` }}'
  vnc_port_max: '{{ user `vnc_vrdp_port_max` }}'
  vnc_port_min: '{{ user `vnc_vrdp_port_min` }}'
#
#                                          __   __  ___   ___  _ __  | |_   ___  _ __
#                                          \ \ / / / __| / _ \| '_ \ | __| / _ \| '__|
#                                           \ V / | (__ |  __/| | | || |_ |  __/| |
#                                            \_/   \___| \___||_| |_| \__| \___||_|
#
- <<: [*builder_common_options]
  name: vsphere-iso
  type: vsphere-iso
  vcenter_server: '{{user `vsphere-server`}}'
  username: '{{user `vsphere-user`}}'
  password: '{{user `vsphere-password`}}'
  insecure_connection: 'true'

  datacenter: '{{user `vsphere-datacenter`}}'
  cluster: '{{user `vsphere-cluster`}}'
  datastore: '{{user `vsphere-datastore`}}'

  vm_name: '{{user `vm_name`}}'
  notes: 'Build via Packer'
  convert_to_template: true
  export:
    force: true
    output_directory: '{{user `output_directory`}}'  

  guest_os_type: 'centos7_64Guest'
  CPUs: 1
  RAM: 1024
  RAM_reserve_all: false
  disk_controller_type: lsilogic
  resource_pool: '{{user `resource-pool`}}'
  storage:
      - disk_size: 20000
        disk_thin_provisioned: true

  iso_urls:
      -  '{{user `iso_path_external`}}/{{user `iso_file`}}'
  iso_checksum: '{{user `iso_checksum`}}'
  network_adapters:
    - network: "S008-ITILAB+STANDARD+STANDARD"
      network_card: "vmxnet3"



description: '{{ user `description` }}'
min_packer_version: 1.6.6

#                  _
#  _ __   ___  ___| |_      _ __  _ __ ___   ___ ___  ___ ___  ___  _ __ ___
# | '_ \ / _ \/ __| __|____| '_ \| '__/ _ \ / __/ _ \/ __/ __|/ _ \| '__/ __|
# | |_) | (_) \__ \ ||_____| |_) | | | (_) | (_|  __/\__ \__ \ (_) | |  \__ \
# | .__/ \___/|___/\__|    | .__/|_|  \___/ \___\___||___/___/\___/|_|  |___/
# |_|                      |_|
post-processors: []
#                       _     _
#  _ __  _ __ _____   _(_)___(_) ___  _ __   ___ _ __ ___
# | '_ \| '__/ _ \ \ / / / __| |/ _ \| '_ \ / _ \ '__/ __|
# | |_) | | | (_) \ V /| \__ \ | (_) | | | |  __/ |  \__ \
# | .__/|_|  \___/ \_/ |_|___/_|\___/|_| |_|\___|_|  |___/
# |_|
provisioners:
- cookbook_paths:
  - "{{template_dir}}/cookbooks"
  guest_os_type: windows
  run_list:
  - packer::disable_uac
  - packer::disable_restore
  - packer::disable_windows_update
  - packer::remove_defender
  - packer::configure_power
  - packer::disable_screensaver
  type: chef-solo
- type: windows-restart
- cookbook_paths:
  - "{{template_dir}}/cookbooks"
  guest_os_type: windows
  run_list:
  - packer::vm_tools
  - packer::features
  - packer::enable_file_sharing
  - packer::enable_remote_desktop
  - packer::ui_tweaks
  type: chef-solo
- type: windows-restart
- cookbook_paths:
  - "{{template_dir}}/cookbooks"
  guest_os_type: windows
  run_list:
  - packer::cleanup
  - packer::defrag
  type: chef-solo
- elevated_password: vagrant
  elevated_user: vagrant
  script: "{{template_dir}}/scripts/cleanup.ps1"
  type: powershell


#                  _       _     _
# __   ____ _ _ __(_) __ _| |__ | | ___  ___
# \ \ / / _` | '__| |/ _` | '_ \| |/ _ \/ __|
#  \ V / (_| | |  | | (_| | |_) | |  __/\__ \
#   \_/ \__,_|_|  |_|\__,_|_.__/|_|\___||___/
variables:
  apt_cache_url: http://myserver:3142
  boot_wait: 3s
  bundle_iso: 'false'
  communicator: ssh
  country: CA
  cpus: '1'
  description: 'Base box for x86_64 Ubuntu Focal Fossa 20.04.x LTS'
  disk_size: '7500'
  domain: ''
  guest_os_type: Ubuntu_64
  headless: 'false'
  host_port_max: '4444'
  host_port_min: '2222'
  http_directory: '.'
  http_port_max: '9000'
  http_port_min: '8000'
# iso_checksum: file:http://releases.ubuntu.com/20.04/SHA256SUMS
  iso_checksum: sha256:443511f6bf12402c12503733059269a2e10dec602916c0a75263e5d990f6bb93
  iso_file: ubuntu-20.04.1-live-server-amd64.iso
  iso_path_external: http://releases.ubuntu.com/20.04
  iso_path_internal: http://myserver:8080/ubuntu
  keep_registered: 'false'
  keyboard: us
  language: en
  locale: en_CA.UTF-8
  memory: '1024'
  min_vagrant_version: 2.2.14
  #output_directory: 'build/{{ isotime "2006-01-02-15-04-05" }}'
  output_directory: 'build/latest'
  packer_cache_dir: '{{ env `PACKER_CACHE_DIR` }}'
  qemu_binary: qemu-system-x86_64
  shutdown_timeout: 5m
  skip_export: 'false'
  ssh_agent_auth: 'false'
  ssh_pwauth: 'true'
  ssh_clear_authorized_keys: 'false'
  ssh_disable_agent_forwarding: 'false'
  ssh_file_transfer_method: scp
  ssh_fullname: Ghost Writer
  ssh_handshake_attempts: '100'
  ssh_keep_alive_interval: 5s
  ssh_password: 1ma63b0rk3d
  ssh_password_crypted: '$6$w5yFawT.$d51yQ513SdzariRCjomBwO9IMtMh6.TjnRwQqTBlOMwGhyyVXlJeYC9kanFp65bpoS1tn9x7r8gLP5Dg4CtEP1'
  ssh_port: '22'
  ssh_pty: 'false'
  ssh_timeout: 60m
  ssh_username: ghost
  start_retry_timeout: 5m
  system_clock_in_utc: 'true'
  timezone: UTC
  userdata_location: template/ubuntu/20.04_focal
  vagrantfile_template: template/ubuntu/20.04_focal/base.vagrant
  version: 0.0.0
  vm_name: base-focal
  vnc_vrdp_bind_address: 10.238.224.102
  vnc_vrdp_port_max: '6000'
  vnc_vrdp_port_min: '5900'
  vsphere-server: "its-vcsa-lab"
  vsphere-user: "itsfe@swatchgroup.net"
  vsphere-password: "Ingress!!"
  vsphere-datacenter: "LABDC_CH"
  vsphere-cluster: "SL5-Lab/SL5SLAB01"
  vsphere-network: "VM Network"
  vsphere-datastore: "NTXCHBI003-HYB-1"
  resource-pool: ""
